# Generated by Django 2.0.7 on 2023-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
