# Generated by Django 4.2.1 on 2023-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_img',
            name='location',
            field=models.CharField(default='ND', max_length=50),
            preserve_default=False,
        ),
    ]
