# Generated by Django 4.2.1 on 2023-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_img_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_img',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload_img',
            name='dateTime',
            field=models.DateField(auto_now=True),
        ),
    ]
